#!/usr/bin/env node
/**
 * Zero-dependency static build.
 *
 *   node tools/build.mjs                       -> writes ./index.html, ./assets/css/site.css, ./assets/js/site.js
 *   node tools/build.mjs --out=/tmp/preview    -> same output into another folder (assets symlinked), for isolated previews
 *   node tools/build.mjs --only=10-hero,50-work -> only those sections (core 00-09 partials are always included)
 *
 * Source layout
 *   src/index.template.html   page shell; <!-- @sections --> marks where partials are inserted
 *   src/sections/NN-name.html section markup, concatenated in filename order
 *   src/css/base/*.css        global styles, then src/css/sections/NN-name.css in filename order
 *   src/js/core/*.js          engine, then src/js/sections/NN-name.js in filename order, then src/js/main.js
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, renameSync, existsSync, symlinkSync, lstatSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, ...v] = a.replace(/^--/, '').split('=');
    return [k, v.length ? v.join('=') : true];
  })
);
const outDir = args.out ? resolve(String(args.out)) : root;
const only = args.only ? String(args.only).split(',').map((s) => s.trim()).filter(Boolean) : null;

const stem = (f) => basename(f).replace(/\.[^.]+$/, '');
const isCore = (f) => /^0\d-/.test(basename(f));
const wanted = (f) => !only || isCore(f) || only.includes(stem(f)) || only.includes(stem(f).replace(/^\d+-/, ''));
const list = (dir, ext) =>
  existsSync(join(root, dir))
    ? readdirSync(join(root, dir)).filter((f) => f.endsWith(ext)).sort().map((f) => join(dir, f))
    : [];
const read = (p) => readFileSync(join(root, p), 'utf8');

function atomicWrite(file, content) {
  mkdirSync(dirname(file), { recursive: true });
  const tmp = `${file}.tmp-${process.pid}-${Math.floor(Math.random() * 1e9)}`;
  writeFileSync(tmp, content);
  renameSync(tmp, file);
}

const banner = (p) => `\n/* ==== ${p} ==== */\n`;
const generated = '/* GENERATED by tools/build.mjs from src/ - edit the sources, not this file. */\n';

// HTML
// Partials are routed by prefix: 00-09 -> before <main> (chrome), 10-94 -> inside <main>, 95-99 -> after <main> (footer).
const sections = list('src/sections', '.html').filter(wanted);
const prefix = (p) => Number(basename(p).slice(0, 2));
const join_ = (arr) => arr.map((p) => `\n<!-- ==== ${p} ==== -->\n${read(p).trim()}\n`).join('');
let html = read('src/index.template.html');
for (const m of ['<!-- @sections:core -->', '<!-- @sections -->', '<!-- @sections:end -->']) {
  if (!html.includes(m)) throw new Error(`template is missing ${m} marker`);
}
html = html
  .replace('<!-- @sections:core -->', () => join_(sections.filter((p) => prefix(p) < 10)))
  .replace('<!-- @sections:end -->', () => join_(sections.filter((p) => prefix(p) >= 95)))
  .replace('<!-- @sections -->', () => join_(sections.filter((p) => prefix(p) >= 10 && prefix(p) < 95)));
html = html.replace('<!-- @generated -->', () => '<!-- GENERATED by tools/build.mjs from src/ - edit the sources, not this file. -->');

// CSS
const css = [...list('src/css/base', '.css'), ...list('src/css/sections', '.css').filter(wanted)]
  .map((p) => banner(p) + read(p).trim() + '\n')
  .join('');

// JS: each file keeps its own scope via an IIFE wrapper.
const js = [...list('src/js/core', '.js'), ...list('src/js/sections', '.js').filter(wanted), 'src/js/main.js']
  .filter((p) => existsSync(join(root, p)))
  .map((p) => `${banner(p)};(function () {\n'use strict';\n${read(p).trim()}\n})();\n`)
  .join('');

atomicWrite(join(outDir, 'index.html'), html);
atomicWrite(join(outDir, 'assets/css/site.css'), generated + css);
atomicWrite(join(outDir, 'assets/js/site.js'), generated + js);

// Isolated previews share the real static assets through symlinks.
if (outDir !== root) {
  for (const d of ['vendor', 'fonts', 'img']) {
    const target = join(outDir, 'assets', d);
    let present = false;
    try { lstatSync(target); present = true; } catch {}
    if (!present) symlinkSync(join(root, 'assets', d), target, 'dir');
  }
}

console.log(`built ${sections.length} sections -> ${outDir === root ? '.' : outDir}`);
